title: Grace and Sterling
email: sam@sampedley.com
description: > # this means to ignore newlines until "baseurl:"
  Grace and Sterling are getting hitched!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://graceandsterling.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
