title: Grace and Sterling
email: sam@sampedley.com
description: >
  Grace and Sterling are getting hitched!
baseurl: ""
url: "https://graceandsterling.com"
google_analytics: UA-50115253-3

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
