runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /(.*)
  static_files: public/\1
  upload: public/(.*)

- url: /.*
  static_files: public/index.html
  upload: public/index.html

skip_files:
- docs/
- node_modules/
- source/
- package-lock.json
- package.json
- readme.md
- webpack.config.js
- .git
- .gitignore
- .DS_Store